version: '3.8'

services:
  generator:
    build: 
      context: .
      dockerfile: Dockerfile
    image: deep_hpdirc:v3

    device_requests:
      - driver: nvidia
        count: all
        capabilities: [gpu]

    volumes: 
      - ./Trained_Models:/workspace/Trained_Models:ro 
      - ./outputs:/outputs