apiVersion: v1
kind: Pod
metadata:
  name: hpdirc-fastsim           # <— pick any DNS-safe name
spec:
  nodeName: gu13.sciclone.wm.edu # <— pick a node with an A40 GPU
  restartPolicy: Never         # one-shot batch: never restart

  # ────── 1. runtime identity ──────
  securityContext:
    runAsUser: 249309          # your Unix UID
    runAsGroup: 50027          # your Unix GID
    fsGroup: 50027             # makes NFS files group-writable

  # ────── 2. where to land the Pod ──────
  nodeSelector:
    kubernetes.io/hostname: gu13.sciclone.wm.edu
    nvidia.com/gpu.product: "NVIDIA-A40"

  # ────── 3. actual container ──────
  containers:
  - name: generator
    image: ghcr.io/mikemartinez13/deep_hpdirc:v3 # <— your pushed image tag

    # Optional arguments to override the defaults in the Dockerfile
    args: 
      - "--config=workspace/config/config_docker.json"
      - "--n_tracks=10000"
      - "--method=MixPK"
      - "--momentum=6"
      - "--theta=95"
      - "--fine_grained_prior" 
      - "--dark_noise"
      - "--dark_rate=22800" 
      - "--use_gpu"
    
    imagePullPolicy: IfNotPresent    
    volumeMounts:
    - name: workspace
      mountPath: /workspace
      
    # - name: results # gives user a writable working directory
    #   mountPath: /outputs
    #   readOnly: false

    - name: nsf-home
      mountPath: /sciclone/home/mcmartinez         # same absolute path
      readOnly: false

    - name: nsf-data
      mountPath: /outputs
      readOnly: false
    
    workingDir: /

    #command: ["python", "-u", "-c", "import os; print('test'); print(os.getcwd()); print(os.listdir())"]

    command: ["python", "workspace/run_simulation.py",
              "--config","workspace/config/config.json",
              "--n_tracks", "10000",
              "--method", "MixPK",
              "--momentum", "6",
              "--theta", "95",
              "--fine_grained_prior",
              "--dark_noise",
              "--dark_rate","22800",
              "--use_gpu"]
    
    # ─── 3a. resource requests/limits ───
    resources:
      requests:
        cpu: "8"
        memory: "32Gi"
        nvidia.com/gpu: "1"
      limits:
        cpu: "8"
        memory: "32Gi"
        nvidia.com/gpu: "1"

  # ────── 4. volumes backed by NFS ──────
  volumes:
  - name: workspace
    nfs:
      server: 128.239.56.166
      path: /sciclone/home/mcmartinez/Deep_hpDIRC
  - name: nsf-home
    nfs:
      server: 128.239.56.166
      path: /sciclone/home/mcmartinez
  - name: nsf-data
    nfs:
      server: 128.239.56.30
      path: /sciclone/data10/mcmartinez
    # gives user a writable working directory
  # so users can retrieve outputs after job completion
  # - name: results
  #   persistentVolumeClaim:
  #     claimName: hpdirc-outputs-pvc
