apiVersion: batch/v1
kind: Job
metadata:
  name: hpdirc-fastsim           # <— pick any DNS-safe name
spec:
  template:
    metadata:
      labels:
        app: hpdirc-fastsim
    spec:
      restartPolicy: Never         # one-shot batch: never restart

      # ────── 1. runtime identity ──────
      securityContext:
        runAsUser: 249309          # your Unix UID
        runAsGroup: 50027          # your Unix GID
        fsGroup: 50027             # makes NFS files group-writable

      # ────── 2. where to land the Pod ──────
      nodeSelector:
        nvidia.com/gpu.product: "NVIDIA-A40"

      # ────── 3. actual container ──────
      containers:
      - name: generator
        image: ghcr.io/mcmartinez/deep_hpdirc:latest # <— your pushed image tag
        imagePullPolicy: IfNotPresent    
        workingDir: /workspace

        # If your Dockerfile already has an ENTRYPOINT that starts the job,
        # you can omit 'command'.  Otherwise set it explicitly:
        command: ["python","-m","run_simulation.py",
                  "--config","/workspace/config/config.json","
                  --n_tracks", "1e5",
                  "--method", "MixPK",
                  "--momentum", "6",
                  "--theta", "95",
                  "--fine_grained_prior", "True",
                  "dark_noise","False",
                  "--dark_rate","22800",
                  "--use_gpu", "False"]

        # ─── 3a. resource requests/limits ───
        resources:
          requests:
            cpu: "14"
            memory: "88Gi"
            nvidia.com/gpu: "1"
          limits:
            cpu: "14"
            memory: "88Gi"
            nvidia.com/gpu: "1"

        # ─── 3b. volume mounts inside the container ───
        volumeMounts:
        - name: nsf-home
          mountPath: /sciclone/home/mcmartinez         # same absolute path
          readOnly: false
        - name: nsf-data
          mountPath: /sciclone/data10/mcmartinez
          readOnly: false

      # ────── 4. volumes backed by NFS ──────
      volumes:
      - name: nsf-home
        nfs:
          server: 128.239.56.166
          path: /sciclone/home/mcmartinez
      - name: nsf-data
        nfs:
          server: 128.239.56.30
          path: /sciclone/data10/mcmartinez
