#!/bin/tcsh
#PBS -N FS_Kaons
#PBS -l nodes=1:hima:gpu:ppn=20
#PBS -l walltime=50:00:00
#PBS -j oe

cd $PBS_O_WORKDIR

module load anaconda3/2021.11
module load cuda/11.7
conda activate ptorch
python /sciclone/home/jgiroux/Cherenkov_FastSim/train_fs.py --config /sciclone/home/jgiroux/Cherenkov_FastSim/config/config.json


